### ISSUE TITLE
Font not being set

### ISSUE THREAD

**Issue by arunnav** [Word-DocX/DocX#2]
Font is always set to Calibri regardless of what is set in code. This behaviour is visible even in the Hello World example.

Edit: 
Testing environment -
Visual Studio 2010
Windows XP and Windows 7 64 bit

In addition to the Fonts not working, when using lists, the color, size etc are also not being set although they are working for normal paragraphs/text.

**Comment by faizanj** [comment]
arunnav, can you check if you are encountering the same issue with the original source found at http://docx.codeplex.com/ ?

**Comment by arunnav** [comment]
No, with the original source, fonts work correct.

**Comment by faizanj** [comment]
Just an update - I am looking at this issue and so far haven't been able to track down what's causing the font type not to be set in normal paragraphs because the code for font type hasn't been changed in this version of DocX but I will continue to track this down.

**Comment by faizanj** [comment]
I have added a fix in the branch docx-font-style-fix which allows a paragraph texts' font family to be set and read. I am not sure how it was working in the original DocX source.

**Comment by faizanj** [comment]
Added capability to set font-styles.
